services:
  database-init:
    build: ./database
    profiles:
      - init
    env_file:
      - .env
    command: python init_sqlserver.py --reset

  api-gateway:
    build: ./api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - auth-service
      - users-service
      - restaurant-service
      - catalog-service
      - cart-service
      - orders-service
      - payments-service
      - delivery-service

  auth-service:
    build: ./services/auth_service
    ports:
      - "${AUTH_SERVICE_PORT}:8000"
    env_file:
      - .env

  users-service:
    build: ./services/users-service
    ports:
      - "${USERS_SERVICE_PORT}:8000"
    env_file:
      - .env

  restaurant-service:
    build: ./services/restaurant-service
    ports:
      - "${RESTAURANT_SERVICE_PORT}:8000"
    env_file:
      - .env
    volumes:
      - ./services/restaurant-service/uploads:/app/uploads

  catalog-service:
    build: ./services/catalog-service
    ports:
      - "${CATALOG_SERVICE_PORT}:8000"
    env_file:
      - .env
    volumes:
      - ./services/catalog-service/uploads:/app/uploads

  cart-service:
    build: ./services/cart-service
    ports:
      - "${CART_SERVICE_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - catalog-service
      - orders-service

  orders-service:
    build: ./services/orders-service
    ports:
      - "${ORDERS_SERVICE_PORT}:8000"
    env_file:
      - .env

  payments-service:
    build: ./services/payments-service
    ports:
      - "${PAYMENTS_SERVICE_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - orders-service

  delivery-service:
    build: ./services/delivery-service
    ports:
      - "${DELIVERY_SERVICE_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - users-service
      - orders-service
