server.port=${SERVER_PORT:8000}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlite:../../database/integrador.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
