server.port=${SERVER_PORT:8000}
spring.datasource.url=jdbc:sqlserver://${RDS_HOST}:${RDS_PORT};databaseName=${RDS_DB};encrypt=true;trustServerCertificate=false;loginTimeout=30
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=${RDS_USER}
spring.datasource.password=${RDS_PASSWORD}
spring.datasource.hikari.connection-timeout=30000
